baseurl = "http://kbenoit.github.io/testing/"
languageCode = "en-uk"
title = "Text Analysis Using R"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Kenneth Benoit"
	description = "Text Analysis Using R."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/kbenoit/testing"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	PygmentsCodeFences = true
	pygmentsuseclasses = true

	[params.palette]
    	primary = "indigo"
    	accent  = "B0BEC5"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "kenbenoit"
	github  = "kbenoit"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

[[menu.main]]
	name   = "Read me"
	url    = "readme/"
	weight = 35


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
	PygmentsCodeFences = true